#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 80
spring:
  profiles: dev # 开发环境
  application:
    name: microservice-config-zuul-gateway			# ******服务名*******
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true 
zuul:
  routes:
    weather-report: # 路由名称，名称任意，保持所有路由名称唯一
      path: /report/** # 访问路径
      serviceId: microservice-config-report-service# 指定服务ID，会自动从Eureka中找到此服务的ip和端 口
      stripPrefix: false # 代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时 请求 /product/get/1，代理转发到/get/1

---
server:
  port: 80
spring:
  profiles: prod # 生产环境
  application:
    name: microservice-config-zuul-gateway			# ******服务名*******

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true 
zuul:
  routes:
    weather-report: # 路由名称，名称任意，保持所有路由名称唯一
      path: /report/** # 访问路径
      serviceId: microservice-config-report-service# 指定服务ID，会自动从Eureka中找到此服务的ip和端 口
      stripPrefix: false # 代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时 请求 /product/get/1，代理转发到/get/1
